### ISSUE TITLE
No plugins

### ISSUE THREAD

**Issue by KR4HBQ** [GregThib/ttrss-tumblr-gdpr#11]
I have tried 2.1 and 2.0 same issue - my plugins list disappears.

**Comment by GregThib** [comment]
Wow. Can you tell me more ?
Which plugins list ? The one on configuration tab ?
Could you provide a screenshot ?

**Comment by bipokot** [comment]
According to [this comment](https://discourse.tt-rss.org/t/change-on-tumblr-rss-feeds-not-working/1158/41), the issue is that you use old version of tt-rss. In that case, you may see messages `Undefined class constant 'HOOK_FEED_BASIC_INFO'` in your tt-rss error log.

I am not sure though, as I experience the same issue but had not fixed it yet.

**Comment by KR4HBQ** [comment]
Yup, I was running an old version (15.x) and updating it fixed the problem with the plugin. 

Thanks @bipokot  and fair warning, make sure you have a backup of your database before you upgrade.
