### ISSUE TITLE
Plugin doesn't work

### ISSUE THREAD

**Issue by jabacrack** [GregThib/ttrss-tumblr-gdpr#4]
Hi, I install and activate your plugin on tt-rss v17.12 (82152bd) and it doesn't work. If I try to run update.php in debug mode I receive a bunch of parsing errors and after this in tt-rss system log I get error "E_WARNING (2) | classes/rssutils.php:446 | gzdecode(): data error"
Do you have any suggestions how to fix it?

**Comment by GregThib** [comment]
Hi,
sorry for the long time before I can take a look. If i'm right, this problem is the same you exposed on the [TT-RSS forum](https://discourse.tt-rss.org/t/change-on-tumblr-rss-feeds-not-working/1158/74) ?

It's very hard to reply without more informations. BUT, the gzdecode() function is called after a feed is fetched without curl. If you don't have curl installed and activated in you php run environment, the plugin is not available as it use the curl library for posting data and retrieve cookie.

Please, comment.

**Comment by jabacrack** [comment]
Yes, this is same question. Thank you for help. I install curl but doesn't install extension for php.
